### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by ararslan** [JuliaMath/QuadGK.jl#1]
@stevengj Do you have any input on what should be done here before this is tagged and registered?

**Comment by stevengj** [comment]
The docs links seems to be broken.

**Comment by ararslan** [comment]
Stable should be a 404 until a release is tagged, since Documenter only builds stable on tag commits. Latest works for me. Does it not for you?

**Comment by stevengj** [comment]
Since you're exporting `gauss` and `kronrod`, those functions need docstrings.

Also probably define
```jl
gauss(N::Integer) = gauss(Float64, N)
kronrod(N::Integer) = kronrod(Float64, N)
```

The README should probably link to https://github.com/ajt60gaibb/FastGaussQuadrature.jl for (non-adaptive) Gauss quadrature with more weight functions and for high orders N, since the routines here are O(N^2) whereas the ones in FastGaussQuadrature are O(N).  On the other hand, the routines here support arbitrary precision, and include generation of the nested Gauss-Kronrod rules.

**Comment by stevengj** [comment]
Should also grab the patches from JuliaLang/julia#19627

**Comment by stevengj** [comment]
Also link https://github.com/stevengj/Cubature.jl and https://github.com/giordano/Cuba.jl for people wanting multidimensional integration.

**Comment by ararslan** [comment]
Should `gauss` and `kronrod` be exported? I export them here because they're exported from `Base.QuadGK`, but only `quadgk` ends up getting exported from `Base`.

**Comment by stevengj** [comment]
I think it makes sense to export them, since they are useful functions by themselves.  Too specialized to export in Base, but in a QuadGK package they make sense.

**Comment by ararslan** [comment]
Do you know of a better way to preserve the authorship information for the change in 19627 than downloading the diff as a patch and editing it by hand?

**Comment by stevengj** [comment]
Not unless @ajkeller34 wants to resubmit his PR to this repo.
