### ISSUE TITLE
Near singular integral with complex values

### ISSUE THREAD

**Issue by linwaytin** [JuliaMath/QuadGK.jl#123]
quadgk can deal with complex-valued functions directly, but the results can be quite different from doing the real and imaginary parts separately. Consider the function with a pole near the real axis: `1/(x-im*1e-5)`
```julia
julia> quadgk(x->1/(x-im*1e-5), -Inf, Inf, order=51)
(-9.126033262418787e-14 + 3.3034266906330165im, 3.774038598116951)
```
The imag part should be π. 
On the other hand, if I do the real and imag parts separately, the results are quite good:
```julia
julia> quadgk(x->1/(x-im*1e-5)|>real, -Inf, Inf, order=51)
(-1.0969003483296547e-13, 3.432351637542838)

julia> quadgk(x->1/(x-im*1e-5)|>imag, -Inf, Inf, order=51)
(3.141592653589791, 9.641704108183431e-9)
```
Moreover, if instead of `Inf` we do a big interval, the results are quite good!
```julia
julia> quadgk(x->1/(x-im*1e-5), -100, 100, order=51)
(3.3306690738754696e-16 + 3.141592453589788im, 6.422613900903478e-10)
```
My guess is that the mapping from `(-Inf, Inf)` to a finite domain has some subtle issue.
In the following, I do the integral over the real part, which is zero from cancellation so it's a difficult one.
I try the `order=51, 61, 71, 81, ... , 121` sometimes the results are good, sometimes are bad.  
```julia
julia> quadgk(x->1/(x-im*1e-5)|>real, -Inf, Inf, order=51)
(-1.0969003483296547e-13, 3.432351637542838)

julia> quadgk(x->1/(x-im*1e-5)|>real, -Inf, Inf, order=61)
(5.96189764223709e-14, 1.5603599372549275)

julia> quadgk(x->1/(x-im*1e-5)|>real, -Inf, Inf, order=71)
(0.6066668151458118, 4.035418458391775)

julia> quadgk(x->1/(x-im*1e-5)|>real, -Inf, Inf, order=81)
(6.428191312579656e-14, 2.5661629084853166)

julia> quadgk(x->1/(x-im*1e-5)|>real, -Inf, Inf, order=91)
(0.6119258208073088, 5.400072718358128)

julia> quadgk(x->1/(x-im*1e-5)|>real, -Inf, Inf, order=101)
(0.5966146143322891, 3.9847943029871207)

julia> quadgk(x->1/(x-im*1e-5)|>real, -Inf, Inf, order=111)
(-6.129541318955489e-13, 2.874924521354071)

julia> quadgk(x->1/(x-im*1e-5)|>real, -Inf, Inf, order=121)
(-7.09432512735475e-14, 1.51281327594176)
```
On the other hand, if I use a big number, say `1000` to replace `Inf`, the results are all good.

So it seems using `Inf` should be careful, and doing real and imag parts separately might help in some cases.

**Comment by stevengj** [comment]
A basic problem with this integrand is that it decays too slowly for it to be [absolutely integrable](https://encyclopediaofmath.org/wiki/Absolutely_integrable_function).   That is, if we look at
$$
\frac{1}{x - i\delta} = \frac{x}{x^2 + \delta^2} + i\frac{\delta}{x^2 + \delta^2}
$$
then the imaginary part goes as $1/x^2$ so it is absolutely convergent — that's why integrating just the imaginary part is fine — but the real part goes as $1/x$ so it is problematic, along with the complex integrand.

In particular, the integral of the real part of this integrand is **not defined** in the sense of Riemann integration.  See, for example [this stackoverflow discussion](https://math.stackexchange.com/questions/2229944/calculate-int-infty-infty-fracx1x2dx-what-is-wrong-with-this) or [this Wikipedia example](https://en.wikipedia.org/wiki/Improper_integral#Cauchy_principal_value).   To define it, you need to do something else, like a Cauchy principal value.  (That's what you are doing if you integrate over a finite domain and take a limit.)

So, this is not a problem with QuadGK — you are giving it an improper integral that *is not even defined* without additional information, which is why it's giving weird results.

**Comment by linwaytin** [comment]
If I understand correctly, the domain `(-Inf, Inf)` is transformed to `(-1, 1)` symmetrically in QuadGK, so I would expect that the regulation is the same as like `(-100, 100)` and should give zero.

**Comment by stevengj** [comment]
No, because the transformation of the infinite domain to the finite domain is a singular change of variables — it's *equivalent* to the original integral, so it is still not Riemann integrable in your case.

Whereas simply truncating the domain, e.g. to (-100,100), gives something Riemann integrable.

**Comment by linwaytin** [comment]
Ok...my wording is not good, sorry about that. What I want to say is that on a computer I would expect the improper integral means $\lim_{a\to\infty} \int_{-a}^{a}$. And if the coordinate transformation is symmetric, I would expect the quadrature should give 0 for this example. In scipy and octave, this is the behavior. The random behavior shown above means that the code treats the $(-\infty, 0)$ and $(0, \infty)$ differently, which is what I am worried about. 

Let's consider $\frac{x}{(x^2 + \delta)(x^2+1)^{0.001}}$, which converges, but the quadrature gives the following. 
```julia
julia> function g(x)
       x/(x^2+1e-10)/(x^2+1)^0.001
       end
g (generic function with 1 method)

julia> quadgk(g, -Inf, Inf, order=91)
(-0.5678119158615688, 5.159854576084976)
```
If the code treats the positive and negative parts the same, it should be exactly zero. 

I believe that these are just edge cases, but maybe it is worth knowing why.

**Comment by stevengj** [comment]
> What I want to say is that on a computer I would expect the improper integral means

So, you should get a completely different value for the integral if you do a change of variables $y = x+1$?

No matter how you slice it, you are going to run into seeming paradoxes by asking a question to which the answer is ill-defined.
