### ISSUE TITLE
Incorrect results

### ISSUE THREAD

**Issue by pevnak** [JuliaMath/QuadGK.jl#37]
Hi, I have just tried to integrate a Laplace distribution as
```
using QuadGK, Distributions
pc = Laplace(0, 1)
quadgk(x -> pdf(pc, x), -1e8, 1e8, rtol=1e-8)
(0.0, 0.0)
```

I obtain zero, which is obviously wrong as it should be one. The manual says that I should add an explicit point, when the point is non-smooth, which I do
```
quadgk(x -> pdf(pc, x), -1e8, 0, 1e8, rtol=1e-8)
(0.0, 0.0)
```
But it does not help either. I think that the method just omit to sample around the zero sufficiently.

**Comment by stevengj** [comment]
The problem is that if you integrate from `1e-8` to `1e8` then the initial points are too spread out and it only samples your function PDF where it is close to zero.

Simplest solution: if you want to integrate over the whole real line, integrate over the whole real line.
```
julia> quadgk(x -> pdf(pc, x), -Inf, Inf, rtol=1e-8)
(0.999999999999772, 8.248719550886085e-9)
```

Alternatives include increasing the integration order (the `order` parameter) to increase the number of sample points, breaking the integral into more subintervals to increase the number of initial samples, or doing a coordinate transform on your interval to emphasize the origin (this is what the `-Inf..Inf` algorithm does internally).

**Comment by pevnak** [comment]
Thanks a lot for the clarification.

Tomas
